### ISSUE TITLE
Gitalk 点击 Github 登陆后显示 Error: Request failed with status code 404

### ISSUE THREAD

**Issue by grandyang** [yelog/hexo-theme-3-hexo#111]
![WechatIMG5](https://user-images.githubusercontent.com/8553010/115980287-696a5b80-a540-11eb-9ef9-f270fc614db9.jpeg)

如上图所示，调试了好久都不对，求大神指点～

```
gitalk:
  githubID: grandyang
  repo: blogs
  ClientID: ***
  ClientSecret: ***
  adminUser: grandyang
  distractionFreeMode: true
  language: zh-CN
  perPage: 10
```

放issues的repo：
https://github.com/grandyang/blogs
