### ISSUE TITLE
大纲不能显示4级以下标题

### ISSUE THREAD

**Issue by molu-ggg** [yelog/hexo-theme-3-hexo#98]

**Comment by molu-ggg** [comment]
<img src="https://gitee.com/moluggg/image/raw/master/img/20200809143123.png"/>
还有有些大纲不能显示完整是为什么

**Comment by molu-ggg** [comment]
都怪自己太水了

**Comment by yelog** [comment]
这个是通过配置决定的，在 3-hexo 主题下，修改文件 `_config.yml`，找到如下参数进行调整 现在的最大深度

```yml
##########自定义样式设置##############
# Table of contents | 文章目录
toc:
  max_depth: 3  # 1 - 6 (h1-h6) 目录最大级数
```
